# config/deploy.yml
service: buzzwallhq
image: donaldlee50/buzzwallhq
builder:
  arch: amd64
servers:
  web:
    hosts:
      - 5.78.128.143
    options:
      "add-host": host.docker.internal:host-gateway
      publish:
        - "443:443"
      volume:
        - "/root/acme.json:/letsencrypt/acme.json"
    labels:
      traefik.http.routers.buzzwallhq.entrypoints: websecure
      traefik.http.routers.buzzwallhq_secure.rule: "Host(`buzzwallhq.com`) || Host(`www.buzzwallhq.com`)"
      traefik.http.routers.buzzwallhq_secure.tls: true
      traefik.http.services.buzzwallhq.loadbalancer.server.port: 3000
      traefik.http.routers.buzzwallhq.tls.certresolver: letsencrypt
      traefik.http.routers.buzzwallhq.tls.domains[0].main: buzzwallhq.com
      traefik.http.routers.buzzwallhq.tls.domains[0].sans: www.buzzwallhq.com
  worker:
    hosts:
      - 5.78.128.143
    cmd: bundle exec sidekiq
registry:
  username: donaldlee50
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 5.78.128.143
    POSTGRES_USER: postgres
    POSTGRES_DB: buzzwallhq_production
    REDIS_HOST: 5.78.128.143
    TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
    TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
    TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
    TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
    TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_PERMANENT: "true"
    TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: "donaldlee50@gmail.com"
    TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE: "/letsencrypt/acme.json"
    TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE: "true"
    TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT: web
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL
ssh:
  user: root
accessories:
  db:
    image: postgres:16
    host: 5.78.128.143
    port: 5432
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: buzzwallhq_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    roles:
      - web
      - worker
    port: 6379
    directories:
      - data:/data