# config/schedule.yml

find_tiktok_buzzes_daily:
  cron: "30 5 * * *" # Every day at 5:30 AM
  class: FindTiktokBuzzesDailyWorker

find_tiktok_buzzes_weekly:
  cron: "0 5 * * 0" # Every Sunday at 5:00 AM
  class: FindTiktokBuzzesWeeklyWorker

find_tiktok_buzzes_monthly:
  cron: "0 0 1 * *" # On the 1st of every month at midnight
  class: FindTiktokBuzzesMonthlyWorker